'use client';

import React, { useState } from 'react';
import { X, FileText, Download, Loader2, FileSpreadsheet } from 'lucide-react';
import axiosInstance from '@/lib/axios';
import { jsPDF } from 'jspdf';

interface DailyCashReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  storeId: string;
  storeName: string;
  darkMode?: boolean;
}

const DailyCashReportModal: React.FC<DailyCashReportModalProps> = ({
  isOpen,
  onClose,
  storeId,
  storeName,
  darkMode = false,
}) => {
  const [format, setFormat] = useState<'csv' | 'pdf'>('csv');
  const [loading, setLoading] = useState(false);

  if (!isOpen) return null;

  const generateReport = async () => {
    if (!storeId) return;

    setLoading(true);
    try {
      const response = await axiosInstance.get(`/reporting/daily-sales?store_id=${storeId}`);
      if (response.data.success) {
        const data = response.data.data;
        
        if (format === 'csv') {
          downloadCSV(data);
        } else {
          downloadPDF(data);
        }
        onClose();
      }
    } catch (error) {
      console.error('Error generating daily report:', error);
      alert('Failed to generate report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const downloadCSV = (data: any) => {
    const csvContent = [
      ['Date', data.date],
      ['Branch', data.branch],
      ['Total Sales', data.total_sales.toFixed(2)],
      ['Cash', data.cash.toFixed(2)],
      ['Card', data.card.toFixed(2)],
      ['Bkash', data.bkash.toFixed(2)],
      ['Nagad', data.nagad.toFixed(2)],
    ].map(e => e.join(',')).join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `daily-sales-${data.branch}-${data.date}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const downloadPDF = (data: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Indigo-600
    doc.text('ERRUM V2', 105, 20, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setTextColor(31, 41, 55); // Gray-800
    doc.text('Daily Cash Report', 105, 30, { align: 'center' });
    
    // Body Info
    doc.setFontSize(12);
    doc.setTextColor(75, 85, 99); // Gray-600
    doc.text(`Date: ${data.date}`, 20, 45);
    doc.text(`Branch: ${data.branch}`, 20, 52);
    
    doc.setDrawColor(229, 231, 235); // Gray-200
    doc.setLineWidth(0.5);
    doc.line(20, 58, 190, 58);
    
    // Report Data
    doc.setFontSize(13);
    doc.setTextColor(31, 41, 55);
    
    const startY = 70;
    const rowHeight = 10;
    
    const rows = [
      ['Total Sales', data.total_sales],
      ['Cash', data.cash],
      ['Card', data.card],
      ['Bkash', data.bkash],
      ['Nagad', data.nagad],
    ];

    rows.forEach((row, i) => {
      const y = startY + (i * rowHeight);
      doc.text(String(row[0]), 20, y);
      doc.text(`Tk. ${Number(row[1]).toFixed(2)}`, 190, y, { align: 'right' });
      
      if (i < rows.length - 1) {
        doc.setDrawColor(243, 244, 246); // Gray-100
        doc.line(20, y + 3, 190, y + 3);
      }
    });
    
    doc.setDrawColor(79, 70, 229);
    doc.line(20, startY + (rows.length * rowHeight), 190, startY + (rows.length * rowHeight));
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175); // Gray-400
    doc.text('Generated by Errum V2 POS System', 105, 280, { align: 'center' });
    
    doc.save(`daily-sales-${data.branch}-${data.date}.pdf`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
      <div className={`w-full max-w-md ${darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'} rounded-2xl shadow-2xl border p-6 animate-in zoom-in-95 duration-200`}>
        <div className="flex items-center justify-between mb-6">
          <h2 className={`text-xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
            Generate Daily Cash Report
          </h2>
          <button
            onClick={onClose}
            className={`p-2 rounded-full hover:${darkMode ? 'bg-gray-700' : 'bg-gray-100'} transition-colors`}
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        <p className={`text-sm mb-6 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
          Generate a summary of all POS transactions for today in <strong>{storeName}</strong>.
        </p>

        <div className="grid grid-cols-2 gap-4 mb-8">
          <button
            onClick={() => setFormat('csv')}
            className={`flex flex-col items-center gap-3 p-4 rounded-xl border-2 transition-all ${
              format === 'csv'
                ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-900/20'
                : 'border-transparent bg-gray-50 dark:bg-gray-700/50 hover:bg-gray-100 dark:hover:bg-gray-700'
            }`}
          >
            <div className={`p-2 rounded-lg ${format === 'csv' ? 'bg-indigo-600 text-white' : 'bg-green-100 text-green-600 dark:bg-green-900/40 dark:text-green-400'}`}>
              <FileSpreadsheet className="w-6 h-6" />
            </div>
            <span className={`text-sm font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>CSV Spreadsheet</span>
          </button>

          <button
            onClick={() => setFormat('pdf')}
            className={`flex flex-col items-center gap-3 p-4 rounded-xl border-2 transition-all ${
              format === 'pdf'
                ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-900/20'
                : 'border-transparent bg-gray-50 dark:bg-gray-700/50 hover:bg-gray-100 dark:hover:bg-gray-700'
            }`}
          >
            <div className={`p-2 rounded-lg ${format === 'pdf' ? 'bg-indigo-600 text-white' : 'bg-red-100 text-red-600 dark:bg-red-900/40 dark:text-red-400'}`}>
              <FileText className="w-6 h-6" />
            </div>
            <span className={`text-sm font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>PDF Document</span>
          </button>
        </div>

        <div className="flex flex-col gap-3">
          <button
            onClick={generateReport}
            disabled={loading || !storeId}
            className="w-full h-12 flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white font-bold rounded-xl shadow-lg shadow-indigo-200 dark:shadow-none transition-all active:scale-[0.98]"
          >
            {loading ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Download className="w-5 h-5" />
            )}
            {loading ? 'Generating...' : 'Generate Report'}
          </button>
          
          <button
            onClick={onClose}
            className={`w-full h-11 text-sm font-medium ${darkMode ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-700'} transition-colors`}
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
};

export default DailyCashReportModal;
